### ISSUE TITLE
FileZilla is not opening

### ISSUE THREAD

**Issue by skttl** [roose/Wox.Plugin.OpenInFileZilla#2]
Hi

I just tried this cool plugin.

My sites are listed fine, but FileZille never opens, no matter which site I select.

FileZilla is installed at C:\Programmer\FileZilla FTP Client, but I saw in the source, that you use the %programfiles% variable, so it should be able to find it.

Any ideas whats wrong?

FileZilla version is 3.18.0

**Comment by skttl** [comment]
I think theres something wrong with my #programfiles% variable. It resolves to c:\Program Files (x86)

**Comment by roose** [comment]
Hi @skttl, if you have installed the FileZilla in a path different from the default path, try last version of plugin please and in config file manually add path to your filezilla.exe. Install new version and type `fz` in Wox.

**Comment by skttl** [comment]
It is the default path, just my windows that's misconfigured. I changed the source file to use the exact path and now it works.

**Comment by roose** [comment]
I'm glad that the problem is solved, anyway in last version of plugin you can change path to `filezilla.exe` or `sitemanager.xml` without change the sources.
